[pytest]
markers =
    basic: basic string matching tests
    character_classes: character classes tests
    counters: tests for bounded repetition (counters)
    unicode: tests for unicode support
    alternation: tests for alternations
    repetition: tests for repetitions (*, +, ?)
    complex: complex regular expressions tests
